version: 2
jobs:
  install:
    working_directory: ~/finalblog
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - run:
          name: ownership
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}
            - v2-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - "./venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
          key: v2-dependencies-{{ checksum "requirements.txt" }}
  lint:
    working_directory: ~/finalblog
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - run:
          name: ownership
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}
            - v2-dependencies-
      - run:
          name: run flake
          command: |
            . venv/bin/activate
            flake8 .

workflows:
  version: 2
  finalblog_flow:
    jobs:
      - install
      - lint:
          requires:
            - install