"""empty message

Revision ID: e1eb555f77e2
Revises: f5240c27540e
Create Date: 2020-04-03 22:08:35.215987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1eb555f77e2'
down_revision = 'f5240c27540e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_post_id_fkey', 'comment', type_='foreignkey')
    op.drop_constraint('comment_user_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('comment_like_user_id_fkey', 'comment_like', type_='foreignkey')
    op.drop_constraint('comment_like_comment_id_fkey', 'comment_like', type_='foreignkey')
    op.create_foreign_key(None, 'comment_like', 'comment', ['comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment_like', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('post_user_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('post_like_post_id_fkey', 'post_like', type_='foreignkey')
    op.drop_constraint('post_like_user_id_fkey', 'post_like', type_='foreignkey')
    op.create_foreign_key(None, 'post_like', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_like', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_like', type_='foreignkey')
    op.drop_constraint(None, 'post_like', type_='foreignkey')
    op.create_foreign_key('post_like_user_id_fkey', 'post_like', 'user', ['user_id'], ['id'])
    op.create_foreign_key('post_like_post_id_fkey', 'post_like', 'post', ['post_id'], ['id'])
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_user_id_fkey', 'post', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'comment_like', type_='foreignkey')
    op.drop_constraint(None, 'comment_like', type_='foreignkey')
    op.create_foreign_key('comment_like_comment_id_fkey', 'comment_like', 'comment', ['comment_id'], ['id'])
    op.create_foreign_key('comment_like_user_id_fkey', 'comment_like', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_user_id_fkey', 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key('comment_post_id_fkey', 'comment', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
